package site.zkd.unnote.model.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import site.zkd.unnote.model.mybatis.bean.CategoryBean;
import site.zkd.unnote.model.mybatis.bean.CategoryBeanExample;

public interface CategoryBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int countByExample(CategoryBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int deleteByExample(CategoryBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("categoryId") Long categoryId, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int insert(CategoryBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int insertSelective(CategoryBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    List<CategoryBean> selectByExampleWithRowbounds(CategoryBeanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    List<CategoryBean> selectByExample(CategoryBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    CategoryBean selectByPrimaryKey(@Param("categoryId") Long categoryId, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CategoryBean record, @Param("example") CategoryBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CategoryBean record, @Param("example") CategoryBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CategoryBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CategoryBean record);
}