package site.zkd.unnote.model.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import site.zkd.unnote.model.mybatis.bean.LabelBean;
import site.zkd.unnote.model.mybatis.bean.LabelBeanExample;

public interface LabelBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int countByExample(LabelBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int deleteByExample(LabelBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("labelId") Long labelId, @Param("userId") Long userId, @Param("articleId") Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int insert(LabelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int insertSelective(LabelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    List<LabelBean> selectByExampleWithRowbounds(LabelBeanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    List<LabelBean> selectByExample(LabelBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    LabelBean selectByPrimaryKey(@Param("labelId") Long labelId, @Param("userId") Long userId, @Param("articleId") Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LabelBean record, @Param("example") LabelBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LabelBean record, @Param("example") LabelBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LabelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LabelBean record);
}