package site.zkd.unnote.model.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import site.zkd.unnote.model.mybatis.bean.UserBean;
import site.zkd.unnote.model.mybatis.bean.UserBeanExample;

public interface UserBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int countByExample(UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int deleteByExample(UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int insert(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int insertSelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    List<UserBean> selectByExampleWithRowbounds(UserBeanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    List<UserBean> selectByExample(UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    UserBean selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBean record, @Param("example") UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBean record, @Param("example") UserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBean record);
}