package site.zkd.unnote.model.mybatis.bean;

import java.io.Serializable;
import java.util.Date;

public class ArticleBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_id
     *
     * @mbggenerated
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_author
     *
     * @mbggenerated
     */
    private String articleAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_title
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_create_time
     *
     * @mbggenerated
     */
    private Date articleCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.label_id_all
     *
     * @mbggenerated
     */
    private String labelIdAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.label_name_all
     *
     * @mbggenerated
     */
    private String labelNameAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_status
     *
     * @mbggenerated
     */
    private String articleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_abstract
     *
     * @mbggenerated
     */
    private String articleAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_lastmodified_time
     *
     * @mbggenerated
     */
    private Date articleLastmodifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_istop
     *
     * @mbggenerated
     */
    private Integer articleIstop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_isvisible
     *
     * @mbggenerated
     */
    private Integer articleIsvisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.ping_status
     *
     * @mbggenerated
     */
    private String pingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.post_type
     *
     * @mbggenerated
     */
    private String postType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.post_mime_type
     *
     * @mbggenerated
     */
    private String postMimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.spare_field1
     *
     * @mbggenerated
     */
    private String spareField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.spare_field2
     *
     * @mbggenerated
     */
    private String spareField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.spare_field3
     *
     * @mbggenerated
     */
    private String spareField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.spare_field4
     *
     * @mbggenerated
     */
    private String spareField4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.spare_field5
     *
     * @mbggenerated
     */
    private String spareField5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_content
     *
     * @mbggenerated
     */
    private String articleContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_article.article_content_html
     *
     * @mbggenerated
     */
    private String articleContentHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_id
     *
     * @return the value of t_blog_article.article_id
     *
     * @mbggenerated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_id
     *
     * @param articleId the value for t_blog_article.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.user_id
     *
     * @return the value of t_blog_article.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.user_id
     *
     * @param userId the value for t_blog_article.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_author
     *
     * @return the value of t_blog_article.article_author
     *
     * @mbggenerated
     */
    public String getArticleAuthor() {
        return articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_author
     *
     * @param articleAuthor the value for t_blog_article.article_author
     *
     * @mbggenerated
     */
    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor == null ? null : articleAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_title
     *
     * @return the value of t_blog_article.article_title
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_title
     *
     * @param articleTitle the value for t_blog_article.article_title
     *
     * @mbggenerated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_create_time
     *
     * @return the value of t_blog_article.article_create_time
     *
     * @mbggenerated
     */
    public Date getArticleCreateTime() {
        return articleCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_create_time
     *
     * @param articleCreateTime the value for t_blog_article.article_create_time
     *
     * @mbggenerated
     */
    public void setArticleCreateTime(Date articleCreateTime) {
        this.articleCreateTime = articleCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.category_id
     *
     * @return the value of t_blog_article.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.category_id
     *
     * @param categoryId the value for t_blog_article.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.label_id_all
     *
     * @return the value of t_blog_article.label_id_all
     *
     * @mbggenerated
     */
    public String getLabelIdAll() {
        return labelIdAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.label_id_all
     *
     * @param labelIdAll the value for t_blog_article.label_id_all
     *
     * @mbggenerated
     */
    public void setLabelIdAll(String labelIdAll) {
        this.labelIdAll = labelIdAll == null ? null : labelIdAll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.label_name_all
     *
     * @return the value of t_blog_article.label_name_all
     *
     * @mbggenerated
     */
    public String getLabelNameAll() {
        return labelNameAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.label_name_all
     *
     * @param labelNameAll the value for t_blog_article.label_name_all
     *
     * @mbggenerated
     */
    public void setLabelNameAll(String labelNameAll) {
        this.labelNameAll = labelNameAll == null ? null : labelNameAll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_status
     *
     * @return the value of t_blog_article.article_status
     *
     * @mbggenerated
     */
    public String getArticleStatus() {
        return articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_status
     *
     * @param articleStatus the value for t_blog_article.article_status
     *
     * @mbggenerated
     */
    public void setArticleStatus(String articleStatus) {
        this.articleStatus = articleStatus == null ? null : articleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_abstract
     *
     * @return the value of t_blog_article.article_abstract
     *
     * @mbggenerated
     */
    public String getArticleAbstract() {
        return articleAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_abstract
     *
     * @param articleAbstract the value for t_blog_article.article_abstract
     *
     * @mbggenerated
     */
    public void setArticleAbstract(String articleAbstract) {
        this.articleAbstract = articleAbstract == null ? null : articleAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_lastmodified_time
     *
     * @return the value of t_blog_article.article_lastmodified_time
     *
     * @mbggenerated
     */
    public Date getArticleLastmodifiedTime() {
        return articleLastmodifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_lastmodified_time
     *
     * @param articleLastmodifiedTime the value for t_blog_article.article_lastmodified_time
     *
     * @mbggenerated
     */
    public void setArticleLastmodifiedTime(Date articleLastmodifiedTime) {
        this.articleLastmodifiedTime = articleLastmodifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_istop
     *
     * @return the value of t_blog_article.article_istop
     *
     * @mbggenerated
     */
    public Integer getArticleIstop() {
        return articleIstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_istop
     *
     * @param articleIstop the value for t_blog_article.article_istop
     *
     * @mbggenerated
     */
    public void setArticleIstop(Integer articleIstop) {
        this.articleIstop = articleIstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_isvisible
     *
     * @return the value of t_blog_article.article_isvisible
     *
     * @mbggenerated
     */
    public Integer getArticleIsvisible() {
        return articleIsvisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_isvisible
     *
     * @param articleIsvisible the value for t_blog_article.article_isvisible
     *
     * @mbggenerated
     */
    public void setArticleIsvisible(Integer articleIsvisible) {
        this.articleIsvisible = articleIsvisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.guid
     *
     * @return the value of t_blog_article.guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.guid
     *
     * @param guid the value for t_blog_article.guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.ping_status
     *
     * @return the value of t_blog_article.ping_status
     *
     * @mbggenerated
     */
    public String getPingStatus() {
        return pingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.ping_status
     *
     * @param pingStatus the value for t_blog_article.ping_status
     *
     * @mbggenerated
     */
    public void setPingStatus(String pingStatus) {
        this.pingStatus = pingStatus == null ? null : pingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.post_type
     *
     * @return the value of t_blog_article.post_type
     *
     * @mbggenerated
     */
    public String getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.post_type
     *
     * @param postType the value for t_blog_article.post_type
     *
     * @mbggenerated
     */
    public void setPostType(String postType) {
        this.postType = postType == null ? null : postType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.post_mime_type
     *
     * @return the value of t_blog_article.post_mime_type
     *
     * @mbggenerated
     */
    public String getPostMimeType() {
        return postMimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.post_mime_type
     *
     * @param postMimeType the value for t_blog_article.post_mime_type
     *
     * @mbggenerated
     */
    public void setPostMimeType(String postMimeType) {
        this.postMimeType = postMimeType == null ? null : postMimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.spare_field1
     *
     * @return the value of t_blog_article.spare_field1
     *
     * @mbggenerated
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.spare_field1
     *
     * @param spareField1 the value for t_blog_article.spare_field1
     *
     * @mbggenerated
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1 == null ? null : spareField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.spare_field2
     *
     * @return the value of t_blog_article.spare_field2
     *
     * @mbggenerated
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.spare_field2
     *
     * @param spareField2 the value for t_blog_article.spare_field2
     *
     * @mbggenerated
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2 == null ? null : spareField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.spare_field3
     *
     * @return the value of t_blog_article.spare_field3
     *
     * @mbggenerated
     */
    public String getSpareField3() {
        return spareField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.spare_field3
     *
     * @param spareField3 the value for t_blog_article.spare_field3
     *
     * @mbggenerated
     */
    public void setSpareField3(String spareField3) {
        this.spareField3 = spareField3 == null ? null : spareField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.spare_field4
     *
     * @return the value of t_blog_article.spare_field4
     *
     * @mbggenerated
     */
    public String getSpareField4() {
        return spareField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.spare_field4
     *
     * @param spareField4 the value for t_blog_article.spare_field4
     *
     * @mbggenerated
     */
    public void setSpareField4(String spareField4) {
        this.spareField4 = spareField4 == null ? null : spareField4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.spare_field5
     *
     * @return the value of t_blog_article.spare_field5
     *
     * @mbggenerated
     */
    public String getSpareField5() {
        return spareField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.spare_field5
     *
     * @param spareField5 the value for t_blog_article.spare_field5
     *
     * @mbggenerated
     */
    public void setSpareField5(String spareField5) {
        this.spareField5 = spareField5 == null ? null : spareField5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_content
     *
     * @return the value of t_blog_article.article_content
     *
     * @mbggenerated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_content
     *
     * @param articleContent the value for t_blog_article.article_content
     *
     * @mbggenerated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_article.article_content_html
     *
     * @return the value of t_blog_article.article_content_html
     *
     * @mbggenerated
     */
    public String getArticleContentHtml() {
        return articleContentHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_article.article_content_html
     *
     * @param articleContentHtml the value for t_blog_article.article_content_html
     *
     * @mbggenerated
     */
    public void setArticleContentHtml(String articleContentHtml) {
        this.articleContentHtml = articleContentHtml == null ? null : articleContentHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", userId=").append(userId);
        sb.append(", articleAuthor=").append(articleAuthor);
        sb.append(", articleTitle=").append(articleTitle);
        sb.append(", articleCreateTime=").append(articleCreateTime);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", labelIdAll=").append(labelIdAll);
        sb.append(", labelNameAll=").append(labelNameAll);
        sb.append(", articleStatus=").append(articleStatus);
        sb.append(", articleAbstract=").append(articleAbstract);
        sb.append(", articleLastmodifiedTime=").append(articleLastmodifiedTime);
        sb.append(", articleIstop=").append(articleIstop);
        sb.append(", articleIsvisible=").append(articleIsvisible);
        sb.append(", guid=").append(guid);
        sb.append(", pingStatus=").append(pingStatus);
        sb.append(", postType=").append(postType);
        sb.append(", postMimeType=").append(postMimeType);
        sb.append(", spareField1=").append(spareField1);
        sb.append(", spareField2=").append(spareField2);
        sb.append(", spareField3=").append(spareField3);
        sb.append(", spareField4=").append(spareField4);
        sb.append(", spareField5=").append(spareField5);
        sb.append(", articleContent=").append(articleContent);
        sb.append(", articleContentHtml=").append(articleContentHtml);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}