package site.zkd.unnote.model.mybatis.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public ArticleBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("article_id is null");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("article_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIdEqualTo(Long value) {
            addCriterion("article_id =", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotEqualTo(Long value) {
            addCriterion("article_id <>", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThan(Long value) {
            addCriterion("article_id >", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("article_id >=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThan(Long value) {
            addCriterion("article_id <", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(Long value) {
            addCriterion("article_id <=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIn(List<Long> values) {
            addCriterion("article_id in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotIn(List<Long> values) {
            addCriterion("article_id not in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdBetween(Long value1, Long value2) {
            addCriterion("article_id between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotBetween(Long value1, Long value2) {
            addCriterion("article_id not between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIsNull() {
            addCriterion("article_author is null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIsNotNull() {
            addCriterion("article_author is not null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEqualTo(String value) {
            addCriterion("article_author =", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotEqualTo(String value) {
            addCriterion("article_author <>", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorGreaterThan(String value) {
            addCriterion("article_author >", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("article_author >=", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorLessThan(String value) {
            addCriterion("article_author <", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorLessThanOrEqualTo(String value) {
            addCriterion("article_author <=", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorLike(String value) {
            addCriterion("article_author like", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotLike(String value) {
            addCriterion("article_author not like", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIn(List<String> values) {
            addCriterion("article_author in", values, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotIn(List<String> values) {
            addCriterion("article_author not in", values, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorBetween(String value1, String value2) {
            addCriterion("article_author between", value1, value2, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotBetween(String value1, String value2) {
            addCriterion("article_author not between", value1, value2, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNull() {
            addCriterion("article_title is null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNotNull() {
            addCriterion("article_title is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleEqualTo(String value) {
            addCriterion("article_title =", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotEqualTo(String value) {
            addCriterion("article_title <>", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThan(String value) {
            addCriterion("article_title >", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThanOrEqualTo(String value) {
            addCriterion("article_title >=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThan(String value) {
            addCriterion("article_title <", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThanOrEqualTo(String value) {
            addCriterion("article_title <=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLike(String value) {
            addCriterion("article_title like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotLike(String value) {
            addCriterion("article_title not like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIn(List<String> values) {
            addCriterion("article_title in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotIn(List<String> values) {
            addCriterion("article_title not in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleBetween(String value1, String value2) {
            addCriterion("article_title between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotBetween(String value1, String value2) {
            addCriterion("article_title not between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeIsNull() {
            addCriterion("article_create_time is null");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeIsNotNull() {
            addCriterion("article_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeEqualTo(Date value) {
            addCriterion("article_create_time =", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeNotEqualTo(Date value) {
            addCriterion("article_create_time <>", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeGreaterThan(Date value) {
            addCriterion("article_create_time >", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("article_create_time >=", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeLessThan(Date value) {
            addCriterion("article_create_time <", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("article_create_time <=", value, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeIn(List<Date> values) {
            addCriterion("article_create_time in", values, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeNotIn(List<Date> values) {
            addCriterion("article_create_time not in", values, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeBetween(Date value1, Date value2) {
            addCriterion("article_create_time between", value1, value2, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andArticleCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("article_create_time not between", value1, value2, "articleCreateTime");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Long value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Long value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Long value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Long> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllIsNull() {
            addCriterion("label_id_all is null");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllIsNotNull() {
            addCriterion("label_id_all is not null");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllEqualTo(String value) {
            addCriterion("label_id_all =", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllNotEqualTo(String value) {
            addCriterion("label_id_all <>", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllGreaterThan(String value) {
            addCriterion("label_id_all >", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllGreaterThanOrEqualTo(String value) {
            addCriterion("label_id_all >=", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllLessThan(String value) {
            addCriterion("label_id_all <", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllLessThanOrEqualTo(String value) {
            addCriterion("label_id_all <=", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllLike(String value) {
            addCriterion("label_id_all like", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllNotLike(String value) {
            addCriterion("label_id_all not like", value, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllIn(List<String> values) {
            addCriterion("label_id_all in", values, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllNotIn(List<String> values) {
            addCriterion("label_id_all not in", values, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllBetween(String value1, String value2) {
            addCriterion("label_id_all between", value1, value2, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelIdAllNotBetween(String value1, String value2) {
            addCriterion("label_id_all not between", value1, value2, "labelIdAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllIsNull() {
            addCriterion("label_name_all is null");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllIsNotNull() {
            addCriterion("label_name_all is not null");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllEqualTo(String value) {
            addCriterion("label_name_all =", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllNotEqualTo(String value) {
            addCriterion("label_name_all <>", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllGreaterThan(String value) {
            addCriterion("label_name_all >", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllGreaterThanOrEqualTo(String value) {
            addCriterion("label_name_all >=", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllLessThan(String value) {
            addCriterion("label_name_all <", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllLessThanOrEqualTo(String value) {
            addCriterion("label_name_all <=", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllLike(String value) {
            addCriterion("label_name_all like", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllNotLike(String value) {
            addCriterion("label_name_all not like", value, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllIn(List<String> values) {
            addCriterion("label_name_all in", values, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllNotIn(List<String> values) {
            addCriterion("label_name_all not in", values, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllBetween(String value1, String value2) {
            addCriterion("label_name_all between", value1, value2, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andLabelNameAllNotBetween(String value1, String value2) {
            addCriterion("label_name_all not between", value1, value2, "labelNameAll");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNull() {
            addCriterion("article_status is null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNotNull() {
            addCriterion("article_status is not null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusEqualTo(String value) {
            addCriterion("article_status =", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotEqualTo(String value) {
            addCriterion("article_status <>", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThan(String value) {
            addCriterion("article_status >", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThanOrEqualTo(String value) {
            addCriterion("article_status >=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThan(String value) {
            addCriterion("article_status <", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThanOrEqualTo(String value) {
            addCriterion("article_status <=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLike(String value) {
            addCriterion("article_status like", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotLike(String value) {
            addCriterion("article_status not like", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIn(List<String> values) {
            addCriterion("article_status in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotIn(List<String> values) {
            addCriterion("article_status not in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusBetween(String value1, String value2) {
            addCriterion("article_status between", value1, value2, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotBetween(String value1, String value2) {
            addCriterion("article_status not between", value1, value2, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractIsNull() {
            addCriterion("article_abstract is null");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractIsNotNull() {
            addCriterion("article_abstract is not null");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractEqualTo(String value) {
            addCriterion("article_abstract =", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractNotEqualTo(String value) {
            addCriterion("article_abstract <>", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractGreaterThan(String value) {
            addCriterion("article_abstract >", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractGreaterThanOrEqualTo(String value) {
            addCriterion("article_abstract >=", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractLessThan(String value) {
            addCriterion("article_abstract <", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractLessThanOrEqualTo(String value) {
            addCriterion("article_abstract <=", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractLike(String value) {
            addCriterion("article_abstract like", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractNotLike(String value) {
            addCriterion("article_abstract not like", value, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractIn(List<String> values) {
            addCriterion("article_abstract in", values, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractNotIn(List<String> values) {
            addCriterion("article_abstract not in", values, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractBetween(String value1, String value2) {
            addCriterion("article_abstract between", value1, value2, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleAbstractNotBetween(String value1, String value2) {
            addCriterion("article_abstract not between", value1, value2, "articleAbstract");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeIsNull() {
            addCriterion("article_lastmodified_time is null");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeIsNotNull() {
            addCriterion("article_lastmodified_time is not null");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeEqualTo(Date value) {
            addCriterion("article_lastmodified_time =", value, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeNotEqualTo(Date value) {
            addCriterion("article_lastmodified_time <>", value, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeGreaterThan(Date value) {
            addCriterion("article_lastmodified_time >", value, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("article_lastmodified_time >=", value, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeLessThan(Date value) {
            addCriterion("article_lastmodified_time <", value, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("article_lastmodified_time <=", value, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeIn(List<Date> values) {
            addCriterion("article_lastmodified_time in", values, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeNotIn(List<Date> values) {
            addCriterion("article_lastmodified_time not in", values, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeBetween(Date value1, Date value2) {
            addCriterion("article_lastmodified_time between", value1, value2, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleLastmodifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("article_lastmodified_time not between", value1, value2, "articleLastmodifiedTime");
            return (Criteria) this;
        }

        public Criteria andArticleIstopIsNull() {
            addCriterion("article_istop is null");
            return (Criteria) this;
        }

        public Criteria andArticleIstopIsNotNull() {
            addCriterion("article_istop is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIstopEqualTo(Integer value) {
            addCriterion("article_istop =", value, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopNotEqualTo(Integer value) {
            addCriterion("article_istop <>", value, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopGreaterThan(Integer value) {
            addCriterion("article_istop >", value, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_istop >=", value, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopLessThan(Integer value) {
            addCriterion("article_istop <", value, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopLessThanOrEqualTo(Integer value) {
            addCriterion("article_istop <=", value, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopIn(List<Integer> values) {
            addCriterion("article_istop in", values, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopNotIn(List<Integer> values) {
            addCriterion("article_istop not in", values, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopBetween(Integer value1, Integer value2) {
            addCriterion("article_istop between", value1, value2, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIstopNotBetween(Integer value1, Integer value2) {
            addCriterion("article_istop not between", value1, value2, "articleIstop");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleIsNull() {
            addCriterion("article_isvisible is null");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleIsNotNull() {
            addCriterion("article_isvisible is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleEqualTo(Integer value) {
            addCriterion("article_isvisible =", value, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleNotEqualTo(Integer value) {
            addCriterion("article_isvisible <>", value, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleGreaterThan(Integer value) {
            addCriterion("article_isvisible >", value, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_isvisible >=", value, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleLessThan(Integer value) {
            addCriterion("article_isvisible <", value, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleLessThanOrEqualTo(Integer value) {
            addCriterion("article_isvisible <=", value, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleIn(List<Integer> values) {
            addCriterion("article_isvisible in", values, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleNotIn(List<Integer> values) {
            addCriterion("article_isvisible not in", values, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleBetween(Integer value1, Integer value2) {
            addCriterion("article_isvisible between", value1, value2, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andArticleIsvisibleNotBetween(Integer value1, Integer value2) {
            addCriterion("article_isvisible not between", value1, value2, "articleIsvisible");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andPingStatusIsNull() {
            addCriterion("ping_status is null");
            return (Criteria) this;
        }

        public Criteria andPingStatusIsNotNull() {
            addCriterion("ping_status is not null");
            return (Criteria) this;
        }

        public Criteria andPingStatusEqualTo(String value) {
            addCriterion("ping_status =", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusNotEqualTo(String value) {
            addCriterion("ping_status <>", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusGreaterThan(String value) {
            addCriterion("ping_status >", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ping_status >=", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusLessThan(String value) {
            addCriterion("ping_status <", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusLessThanOrEqualTo(String value) {
            addCriterion("ping_status <=", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusLike(String value) {
            addCriterion("ping_status like", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusNotLike(String value) {
            addCriterion("ping_status not like", value, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusIn(List<String> values) {
            addCriterion("ping_status in", values, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusNotIn(List<String> values) {
            addCriterion("ping_status not in", values, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusBetween(String value1, String value2) {
            addCriterion("ping_status between", value1, value2, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPingStatusNotBetween(String value1, String value2) {
            addCriterion("ping_status not between", value1, value2, "pingStatus");
            return (Criteria) this;
        }

        public Criteria andPostTypeIsNull() {
            addCriterion("post_type is null");
            return (Criteria) this;
        }

        public Criteria andPostTypeIsNotNull() {
            addCriterion("post_type is not null");
            return (Criteria) this;
        }

        public Criteria andPostTypeEqualTo(String value) {
            addCriterion("post_type =", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeNotEqualTo(String value) {
            addCriterion("post_type <>", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeGreaterThan(String value) {
            addCriterion("post_type >", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeGreaterThanOrEqualTo(String value) {
            addCriterion("post_type >=", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeLessThan(String value) {
            addCriterion("post_type <", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeLessThanOrEqualTo(String value) {
            addCriterion("post_type <=", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeLike(String value) {
            addCriterion("post_type like", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeNotLike(String value) {
            addCriterion("post_type not like", value, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeIn(List<String> values) {
            addCriterion("post_type in", values, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeNotIn(List<String> values) {
            addCriterion("post_type not in", values, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeBetween(String value1, String value2) {
            addCriterion("post_type between", value1, value2, "postType");
            return (Criteria) this;
        }

        public Criteria andPostTypeNotBetween(String value1, String value2) {
            addCriterion("post_type not between", value1, value2, "postType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeIsNull() {
            addCriterion("post_mime_type is null");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeIsNotNull() {
            addCriterion("post_mime_type is not null");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeEqualTo(String value) {
            addCriterion("post_mime_type =", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeNotEqualTo(String value) {
            addCriterion("post_mime_type <>", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeGreaterThan(String value) {
            addCriterion("post_mime_type >", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("post_mime_type >=", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeLessThan(String value) {
            addCriterion("post_mime_type <", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeLessThanOrEqualTo(String value) {
            addCriterion("post_mime_type <=", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeLike(String value) {
            addCriterion("post_mime_type like", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeNotLike(String value) {
            addCriterion("post_mime_type not like", value, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeIn(List<String> values) {
            addCriterion("post_mime_type in", values, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeNotIn(List<String> values) {
            addCriterion("post_mime_type not in", values, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeBetween(String value1, String value2) {
            addCriterion("post_mime_type between", value1, value2, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andPostMimeTypeNotBetween(String value1, String value2) {
            addCriterion("post_mime_type not between", value1, value2, "postMimeType");
            return (Criteria) this;
        }

        public Criteria andSpareField1IsNull() {
            addCriterion("spare_field1 is null");
            return (Criteria) this;
        }

        public Criteria andSpareField1IsNotNull() {
            addCriterion("spare_field1 is not null");
            return (Criteria) this;
        }

        public Criteria andSpareField1EqualTo(String value) {
            addCriterion("spare_field1 =", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1NotEqualTo(String value) {
            addCriterion("spare_field1 <>", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1GreaterThan(String value) {
            addCriterion("spare_field1 >", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1GreaterThanOrEqualTo(String value) {
            addCriterion("spare_field1 >=", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1LessThan(String value) {
            addCriterion("spare_field1 <", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1LessThanOrEqualTo(String value) {
            addCriterion("spare_field1 <=", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1Like(String value) {
            addCriterion("spare_field1 like", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1NotLike(String value) {
            addCriterion("spare_field1 not like", value, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1In(List<String> values) {
            addCriterion("spare_field1 in", values, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1NotIn(List<String> values) {
            addCriterion("spare_field1 not in", values, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1Between(String value1, String value2) {
            addCriterion("spare_field1 between", value1, value2, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField1NotBetween(String value1, String value2) {
            addCriterion("spare_field1 not between", value1, value2, "spareField1");
            return (Criteria) this;
        }

        public Criteria andSpareField2IsNull() {
            addCriterion("spare_field2 is null");
            return (Criteria) this;
        }

        public Criteria andSpareField2IsNotNull() {
            addCriterion("spare_field2 is not null");
            return (Criteria) this;
        }

        public Criteria andSpareField2EqualTo(String value) {
            addCriterion("spare_field2 =", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2NotEqualTo(String value) {
            addCriterion("spare_field2 <>", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2GreaterThan(String value) {
            addCriterion("spare_field2 >", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2GreaterThanOrEqualTo(String value) {
            addCriterion("spare_field2 >=", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2LessThan(String value) {
            addCriterion("spare_field2 <", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2LessThanOrEqualTo(String value) {
            addCriterion("spare_field2 <=", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2Like(String value) {
            addCriterion("spare_field2 like", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2NotLike(String value) {
            addCriterion("spare_field2 not like", value, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2In(List<String> values) {
            addCriterion("spare_field2 in", values, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2NotIn(List<String> values) {
            addCriterion("spare_field2 not in", values, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2Between(String value1, String value2) {
            addCriterion("spare_field2 between", value1, value2, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField2NotBetween(String value1, String value2) {
            addCriterion("spare_field2 not between", value1, value2, "spareField2");
            return (Criteria) this;
        }

        public Criteria andSpareField3IsNull() {
            addCriterion("spare_field3 is null");
            return (Criteria) this;
        }

        public Criteria andSpareField3IsNotNull() {
            addCriterion("spare_field3 is not null");
            return (Criteria) this;
        }

        public Criteria andSpareField3EqualTo(String value) {
            addCriterion("spare_field3 =", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3NotEqualTo(String value) {
            addCriterion("spare_field3 <>", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3GreaterThan(String value) {
            addCriterion("spare_field3 >", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3GreaterThanOrEqualTo(String value) {
            addCriterion("spare_field3 >=", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3LessThan(String value) {
            addCriterion("spare_field3 <", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3LessThanOrEqualTo(String value) {
            addCriterion("spare_field3 <=", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3Like(String value) {
            addCriterion("spare_field3 like", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3NotLike(String value) {
            addCriterion("spare_field3 not like", value, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3In(List<String> values) {
            addCriterion("spare_field3 in", values, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3NotIn(List<String> values) {
            addCriterion("spare_field3 not in", values, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3Between(String value1, String value2) {
            addCriterion("spare_field3 between", value1, value2, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField3NotBetween(String value1, String value2) {
            addCriterion("spare_field3 not between", value1, value2, "spareField3");
            return (Criteria) this;
        }

        public Criteria andSpareField4IsNull() {
            addCriterion("spare_field4 is null");
            return (Criteria) this;
        }

        public Criteria andSpareField4IsNotNull() {
            addCriterion("spare_field4 is not null");
            return (Criteria) this;
        }

        public Criteria andSpareField4EqualTo(String value) {
            addCriterion("spare_field4 =", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4NotEqualTo(String value) {
            addCriterion("spare_field4 <>", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4GreaterThan(String value) {
            addCriterion("spare_field4 >", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4GreaterThanOrEqualTo(String value) {
            addCriterion("spare_field4 >=", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4LessThan(String value) {
            addCriterion("spare_field4 <", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4LessThanOrEqualTo(String value) {
            addCriterion("spare_field4 <=", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4Like(String value) {
            addCriterion("spare_field4 like", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4NotLike(String value) {
            addCriterion("spare_field4 not like", value, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4In(List<String> values) {
            addCriterion("spare_field4 in", values, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4NotIn(List<String> values) {
            addCriterion("spare_field4 not in", values, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4Between(String value1, String value2) {
            addCriterion("spare_field4 between", value1, value2, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField4NotBetween(String value1, String value2) {
            addCriterion("spare_field4 not between", value1, value2, "spareField4");
            return (Criteria) this;
        }

        public Criteria andSpareField5IsNull() {
            addCriterion("spare_field5 is null");
            return (Criteria) this;
        }

        public Criteria andSpareField5IsNotNull() {
            addCriterion("spare_field5 is not null");
            return (Criteria) this;
        }

        public Criteria andSpareField5EqualTo(String value) {
            addCriterion("spare_field5 =", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5NotEqualTo(String value) {
            addCriterion("spare_field5 <>", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5GreaterThan(String value) {
            addCriterion("spare_field5 >", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5GreaterThanOrEqualTo(String value) {
            addCriterion("spare_field5 >=", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5LessThan(String value) {
            addCriterion("spare_field5 <", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5LessThanOrEqualTo(String value) {
            addCriterion("spare_field5 <=", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5Like(String value) {
            addCriterion("spare_field5 like", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5NotLike(String value) {
            addCriterion("spare_field5 not like", value, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5In(List<String> values) {
            addCriterion("spare_field5 in", values, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5NotIn(List<String> values) {
            addCriterion("spare_field5 not in", values, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5Between(String value1, String value2) {
            addCriterion("spare_field5 between", value1, value2, "spareField5");
            return (Criteria) this;
        }

        public Criteria andSpareField5NotBetween(String value1, String value2) {
            addCriterion("spare_field5 not between", value1, value2, "spareField5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_blog_article
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_blog_article
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}