package site.zkd.unnote.model.mybatis.bean;

import java.io.Serializable;
import java.util.Date;

public class CategoryBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.category_parent_id
     *
     * @mbggenerated
     */
    private Long categoryParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.category_istop
     *
     * @mbggenerated
     */
    private Integer categoryIstop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.category_last_update_time
     *
     * @mbggenerated
     */
    private Date categoryLastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.spare_field1
     *
     * @mbggenerated
     */
    private String spareField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.spare_field2
     *
     * @mbggenerated
     */
    private String spareField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.spare_field3
     *
     * @mbggenerated
     */
    private String spareField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.spare_field4
     *
     * @mbggenerated
     */
    private String spareField4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_category.spare_field5
     *
     * @mbggenerated
     */
    private String spareField5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.category_id
     *
     * @return the value of t_blog_category.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.category_id
     *
     * @param categoryId the value for t_blog_category.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.user_id
     *
     * @return the value of t_blog_category.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.user_id
     *
     * @param userId the value for t_blog_category.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.category_name
     *
     * @return the value of t_blog_category.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.category_name
     *
     * @param categoryName the value for t_blog_category.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.category_parent_id
     *
     * @return the value of t_blog_category.category_parent_id
     *
     * @mbggenerated
     */
    public Long getCategoryParentId() {
        return categoryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.category_parent_id
     *
     * @param categoryParentId the value for t_blog_category.category_parent_id
     *
     * @mbggenerated
     */
    public void setCategoryParentId(Long categoryParentId) {
        this.categoryParentId = categoryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.category_istop
     *
     * @return the value of t_blog_category.category_istop
     *
     * @mbggenerated
     */
    public Integer getCategoryIstop() {
        return categoryIstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.category_istop
     *
     * @param categoryIstop the value for t_blog_category.category_istop
     *
     * @mbggenerated
     */
    public void setCategoryIstop(Integer categoryIstop) {
        this.categoryIstop = categoryIstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.category_last_update_time
     *
     * @return the value of t_blog_category.category_last_update_time
     *
     * @mbggenerated
     */
    public Date getCategoryLastUpdateTime() {
        return categoryLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.category_last_update_time
     *
     * @param categoryLastUpdateTime the value for t_blog_category.category_last_update_time
     *
     * @mbggenerated
     */
    public void setCategoryLastUpdateTime(Date categoryLastUpdateTime) {
        this.categoryLastUpdateTime = categoryLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.spare_field1
     *
     * @return the value of t_blog_category.spare_field1
     *
     * @mbggenerated
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.spare_field1
     *
     * @param spareField1 the value for t_blog_category.spare_field1
     *
     * @mbggenerated
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1 == null ? null : spareField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.spare_field2
     *
     * @return the value of t_blog_category.spare_field2
     *
     * @mbggenerated
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.spare_field2
     *
     * @param spareField2 the value for t_blog_category.spare_field2
     *
     * @mbggenerated
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2 == null ? null : spareField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.spare_field3
     *
     * @return the value of t_blog_category.spare_field3
     *
     * @mbggenerated
     */
    public String getSpareField3() {
        return spareField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.spare_field3
     *
     * @param spareField3 the value for t_blog_category.spare_field3
     *
     * @mbggenerated
     */
    public void setSpareField3(String spareField3) {
        this.spareField3 = spareField3 == null ? null : spareField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.spare_field4
     *
     * @return the value of t_blog_category.spare_field4
     *
     * @mbggenerated
     */
    public String getSpareField4() {
        return spareField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.spare_field4
     *
     * @param spareField4 the value for t_blog_category.spare_field4
     *
     * @mbggenerated
     */
    public void setSpareField4(String spareField4) {
        this.spareField4 = spareField4 == null ? null : spareField4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_category.spare_field5
     *
     * @return the value of t_blog_category.spare_field5
     *
     * @mbggenerated
     */
    public String getSpareField5() {
        return spareField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_category.spare_field5
     *
     * @param spareField5 the value for t_blog_category.spare_field5
     *
     * @mbggenerated
     */
    public void setSpareField5(String spareField5) {
        this.spareField5 = spareField5 == null ? null : spareField5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_category
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryId=").append(categoryId);
        sb.append(", userId=").append(userId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", categoryParentId=").append(categoryParentId);
        sb.append(", categoryIstop=").append(categoryIstop);
        sb.append(", categoryLastUpdateTime=").append(categoryLastUpdateTime);
        sb.append(", spareField1=").append(spareField1);
        sb.append(", spareField2=").append(spareField2);
        sb.append(", spareField3=").append(spareField3);
        sb.append(", spareField4=").append(spareField4);
        sb.append(", spareField5=").append(spareField5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}