package site.zkd.unnote.model.mybatis.bean;

import java.io.Serializable;
import java.util.Date;

public class LabelBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.label_id
     *
     * @mbggenerated
     */
    private Long labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.article_id
     *
     * @mbggenerated
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.label_name
     *
     * @mbggenerated
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.label_last_update_time
     *
     * @mbggenerated
     */
    private Date labelLastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.label_parent_id
     *
     * @mbggenerated
     */
    private Long labelParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.label_istop
     *
     * @mbggenerated
     */
    private Integer labelIstop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.spare_field1
     *
     * @mbggenerated
     */
    private String spareField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.spare_field2
     *
     * @mbggenerated
     */
    private String spareField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.spare_field3
     *
     * @mbggenerated
     */
    private String spareField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.spare_field4
     *
     * @mbggenerated
     */
    private String spareField4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_label.spare_field5
     *
     * @mbggenerated
     */
    private String spareField5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.label_id
     *
     * @return the value of t_blog_label.label_id
     *
     * @mbggenerated
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.label_id
     *
     * @param labelId the value for t_blog_label.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.user_id
     *
     * @return the value of t_blog_label.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.user_id
     *
     * @param userId the value for t_blog_label.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.article_id
     *
     * @return the value of t_blog_label.article_id
     *
     * @mbggenerated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.article_id
     *
     * @param articleId the value for t_blog_label.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.label_name
     *
     * @return the value of t_blog_label.label_name
     *
     * @mbggenerated
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.label_name
     *
     * @param labelName the value for t_blog_label.label_name
     *
     * @mbggenerated
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.label_last_update_time
     *
     * @return the value of t_blog_label.label_last_update_time
     *
     * @mbggenerated
     */
    public Date getLabelLastUpdateTime() {
        return labelLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.label_last_update_time
     *
     * @param labelLastUpdateTime the value for t_blog_label.label_last_update_time
     *
     * @mbggenerated
     */
    public void setLabelLastUpdateTime(Date labelLastUpdateTime) {
        this.labelLastUpdateTime = labelLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.label_parent_id
     *
     * @return the value of t_blog_label.label_parent_id
     *
     * @mbggenerated
     */
    public Long getLabelParentId() {
        return labelParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.label_parent_id
     *
     * @param labelParentId the value for t_blog_label.label_parent_id
     *
     * @mbggenerated
     */
    public void setLabelParentId(Long labelParentId) {
        this.labelParentId = labelParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.label_istop
     *
     * @return the value of t_blog_label.label_istop
     *
     * @mbggenerated
     */
    public Integer getLabelIstop() {
        return labelIstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.label_istop
     *
     * @param labelIstop the value for t_blog_label.label_istop
     *
     * @mbggenerated
     */
    public void setLabelIstop(Integer labelIstop) {
        this.labelIstop = labelIstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.spare_field1
     *
     * @return the value of t_blog_label.spare_field1
     *
     * @mbggenerated
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.spare_field1
     *
     * @param spareField1 the value for t_blog_label.spare_field1
     *
     * @mbggenerated
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1 == null ? null : spareField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.spare_field2
     *
     * @return the value of t_blog_label.spare_field2
     *
     * @mbggenerated
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.spare_field2
     *
     * @param spareField2 the value for t_blog_label.spare_field2
     *
     * @mbggenerated
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2 == null ? null : spareField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.spare_field3
     *
     * @return the value of t_blog_label.spare_field3
     *
     * @mbggenerated
     */
    public String getSpareField3() {
        return spareField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.spare_field3
     *
     * @param spareField3 the value for t_blog_label.spare_field3
     *
     * @mbggenerated
     */
    public void setSpareField3(String spareField3) {
        this.spareField3 = spareField3 == null ? null : spareField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.spare_field4
     *
     * @return the value of t_blog_label.spare_field4
     *
     * @mbggenerated
     */
    public String getSpareField4() {
        return spareField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.spare_field4
     *
     * @param spareField4 the value for t_blog_label.spare_field4
     *
     * @mbggenerated
     */
    public void setSpareField4(String spareField4) {
        this.spareField4 = spareField4 == null ? null : spareField4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_label.spare_field5
     *
     * @return the value of t_blog_label.spare_field5
     *
     * @mbggenerated
     */
    public String getSpareField5() {
        return spareField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_label.spare_field5
     *
     * @param spareField5 the value for t_blog_label.spare_field5
     *
     * @mbggenerated
     */
    public void setSpareField5(String spareField5) {
        this.spareField5 = spareField5 == null ? null : spareField5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_label
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", labelId=").append(labelId);
        sb.append(", userId=").append(userId);
        sb.append(", articleId=").append(articleId);
        sb.append(", labelName=").append(labelName);
        sb.append(", labelLastUpdateTime=").append(labelLastUpdateTime);
        sb.append(", labelParentId=").append(labelParentId);
        sb.append(", labelIstop=").append(labelIstop);
        sb.append(", spareField1=").append(spareField1);
        sb.append(", spareField2=").append(spareField2);
        sb.append(", spareField3=").append(spareField3);
        sb.append(", spareField4=").append(spareField4);
        sb.append(", spareField5=").append(spareField5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}