package site.zkd.unnote.model.mybatis.bean;

import java.io.Serializable;
import java.util.Date;

public class OptionsBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.options_id
     *
     * @mbggenerated
     */
    private Long optionsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.options_name
     *
     * @mbggenerated
     */
    private String optionsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.options_values
     *
     * @mbggenerated
     */
    private Integer optionsValues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.options_autoload
     *
     * @mbggenerated
     */
    private Integer optionsAutoload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.options_last_update_time
     *
     * @mbggenerated
     */
    private Date optionsLastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.spare_field1
     *
     * @mbggenerated
     */
    private String spareField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.spare_field2
     *
     * @mbggenerated
     */
    private String spareField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.spare_field3
     *
     * @mbggenerated
     */
    private String spareField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.spare_field4
     *
     * @mbggenerated
     */
    private String spareField4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.spare_field5
     *
     * @mbggenerated
     */
    private String spareField5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_sys_options.options_extend_id
     *
     * @mbggenerated
     */
    private Long optionsExtendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_sys_options
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.options_id
     *
     * @return the value of t_blog_sys_options.options_id
     *
     * @mbggenerated
     */
    public Long getOptionsId() {
        return optionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.options_id
     *
     * @param optionsId the value for t_blog_sys_options.options_id
     *
     * @mbggenerated
     */
    public void setOptionsId(Long optionsId) {
        this.optionsId = optionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.user_id
     *
     * @return the value of t_blog_sys_options.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.user_id
     *
     * @param userId the value for t_blog_sys_options.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.options_name
     *
     * @return the value of t_blog_sys_options.options_name
     *
     * @mbggenerated
     */
    public String getOptionsName() {
        return optionsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.options_name
     *
     * @param optionsName the value for t_blog_sys_options.options_name
     *
     * @mbggenerated
     */
    public void setOptionsName(String optionsName) {
        this.optionsName = optionsName == null ? null : optionsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.options_values
     *
     * @return the value of t_blog_sys_options.options_values
     *
     * @mbggenerated
     */
    public Integer getOptionsValues() {
        return optionsValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.options_values
     *
     * @param optionsValues the value for t_blog_sys_options.options_values
     *
     * @mbggenerated
     */
    public void setOptionsValues(Integer optionsValues) {
        this.optionsValues = optionsValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.options_autoload
     *
     * @return the value of t_blog_sys_options.options_autoload
     *
     * @mbggenerated
     */
    public Integer getOptionsAutoload() {
        return optionsAutoload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.options_autoload
     *
     * @param optionsAutoload the value for t_blog_sys_options.options_autoload
     *
     * @mbggenerated
     */
    public void setOptionsAutoload(Integer optionsAutoload) {
        this.optionsAutoload = optionsAutoload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.options_last_update_time
     *
     * @return the value of t_blog_sys_options.options_last_update_time
     *
     * @mbggenerated
     */
    public Date getOptionsLastUpdateTime() {
        return optionsLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.options_last_update_time
     *
     * @param optionsLastUpdateTime the value for t_blog_sys_options.options_last_update_time
     *
     * @mbggenerated
     */
    public void setOptionsLastUpdateTime(Date optionsLastUpdateTime) {
        this.optionsLastUpdateTime = optionsLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.spare_field1
     *
     * @return the value of t_blog_sys_options.spare_field1
     *
     * @mbggenerated
     */
    public String getSpareField1() {
        return spareField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.spare_field1
     *
     * @param spareField1 the value for t_blog_sys_options.spare_field1
     *
     * @mbggenerated
     */
    public void setSpareField1(String spareField1) {
        this.spareField1 = spareField1 == null ? null : spareField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.spare_field2
     *
     * @return the value of t_blog_sys_options.spare_field2
     *
     * @mbggenerated
     */
    public String getSpareField2() {
        return spareField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.spare_field2
     *
     * @param spareField2 the value for t_blog_sys_options.spare_field2
     *
     * @mbggenerated
     */
    public void setSpareField2(String spareField2) {
        this.spareField2 = spareField2 == null ? null : spareField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.spare_field3
     *
     * @return the value of t_blog_sys_options.spare_field3
     *
     * @mbggenerated
     */
    public String getSpareField3() {
        return spareField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.spare_field3
     *
     * @param spareField3 the value for t_blog_sys_options.spare_field3
     *
     * @mbggenerated
     */
    public void setSpareField3(String spareField3) {
        this.spareField3 = spareField3 == null ? null : spareField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.spare_field4
     *
     * @return the value of t_blog_sys_options.spare_field4
     *
     * @mbggenerated
     */
    public String getSpareField4() {
        return spareField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.spare_field4
     *
     * @param spareField4 the value for t_blog_sys_options.spare_field4
     *
     * @mbggenerated
     */
    public void setSpareField4(String spareField4) {
        this.spareField4 = spareField4 == null ? null : spareField4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.spare_field5
     *
     * @return the value of t_blog_sys_options.spare_field5
     *
     * @mbggenerated
     */
    public String getSpareField5() {
        return spareField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.spare_field5
     *
     * @param spareField5 the value for t_blog_sys_options.spare_field5
     *
     * @mbggenerated
     */
    public void setSpareField5(String spareField5) {
        this.spareField5 = spareField5 == null ? null : spareField5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_sys_options.options_extend_id
     *
     * @return the value of t_blog_sys_options.options_extend_id
     *
     * @mbggenerated
     */
    public Long getOptionsExtendId() {
        return optionsExtendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_sys_options.options_extend_id
     *
     * @param optionsExtendId the value for t_blog_sys_options.options_extend_id
     *
     * @mbggenerated
     */
    public void setOptionsExtendId(Long optionsExtendId) {
        this.optionsExtendId = optionsExtendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_sys_options
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", optionsId=").append(optionsId);
        sb.append(", userId=").append(userId);
        sb.append(", optionsName=").append(optionsName);
        sb.append(", optionsValues=").append(optionsValues);
        sb.append(", optionsAutoload=").append(optionsAutoload);
        sb.append(", optionsLastUpdateTime=").append(optionsLastUpdateTime);
        sb.append(", spareField1=").append(spareField1);
        sb.append(", spareField2=").append(spareField2);
        sb.append(", spareField3=").append(spareField3);
        sb.append(", spareField4=").append(spareField4);
        sb.append(", spareField5=").append(spareField5);
        sb.append(", optionsExtendId=").append(optionsExtendId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}